on:
  push:
    branches: [main, master]

name: quarto-publish.yaml
author: "Daniel Vartanian"

description: |
  Action for protected Quarto site deployment to GitHub Pages
  (Center for Metropolitan Studies (CEM) version).

jobs:
  quarto-publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      LIBARROW_MINIMAL: false
    permissions:
      contents: write
      pages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            cmake gdal-bin libfontconfig1-dev libfreetype6-dev libgdal-dev \
            libglpk-dev libjpeg-dev libpng-dev libsecret-1-dev \
            libudunits2-dev libx11-dev pandoc

      - name: Set up Node.js
        uses: actions/setup-node@v6

      - name: Install staticrypt
        run: npm install -g staticrypt

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto site
        uses: quarto-dev/quarto-actions/render@v2

      - name: Encrypt index
        run: |
          staticrypt index.html \
            --password  ${{ secrets.DECRYPTION_PIN }} --short \
            --remember false \
            --template-color-primary "#014691" \
            --template-color-secondary "#868489" \
            --template-placeholder "Pin" \
            --template-toggle-hide "Hide pin" \
            --template-toggle-show  "Show pin"
          mv encrypted/index.html index.html
          rm -r encrypted

      - name: Publish Quarto site
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
