on:
  push:
    branches: [main, master]

name: quarto-render.yaml

jobs:
  quarto-render:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Set up Node.js
        uses: actions/setup-node@v6

      - name: Install staticrypt
        run: npm install -g staticrypt

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto site
        uses: quarto-dev/quarto-actions/render@v2

      - name: Encrypt index
        run: |
          staticrypt index.html \
            --password  ${{ secrets.DECRYPTION_PASSPHRASE }} --short \
            --remember false \
            --template-color-primary "#014691" \
            --template-color-secondary "#868489" \
            --template-placeholder "Pin" \
            --template-toggle-hide "Hide pin" \
            --template-toggle-show  "Show pin"
          mv encrypted/index.html index.html
          rm -r encrypted

      - name: Publish Quarto site
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
